INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Berthe', 'Tomson', '8639620741', 'btomson0@boston.com', 'Roommate', 1);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Waylan', 'Dilgarno', '8928680574', 'wdilgarno1@ca.gov', 'Cousin', 2);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Averyl', 'Marcroft', '1203590101', 'amarcroft2@ft.com', 'Friend', 3);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Annabel', 'Dallison', '8404798869', 'adallison3@cocolog-nifty.com', 'Sister', 4);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Eddie', 'Testro', '1744176114', 'etestro4@walmart.com', 'Roommate', 5);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Linoel', 'Glynne', '3897710268', 'lglynne5@google.ru', 'Neighbor', 6);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Nelly', 'Farnsworth', '9559226287', 'nfarnsworth6@nature.com', 'Grandmother', 7);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Derick', 'Meenehan', '3614612849', 'dbendig7@dailymotion.com', 'Father', 8);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Lilian', 'Revely', '1072554563', 'lrevely8@drupal.org', 'Significant other', 9);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Dorey', 'Denney', '8671141537', 'dhawes9@nsw.gov.au', 'Spouse', 10);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Etti', 'Baudichon', '5773192449', 'ebaudichona@ucoz.ru', 'Friend', 11);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Tobi', 'Pedrielli', '6867706388', 'tpedriellib@addtoany.com', 'Significant other', 12);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Welch', 'Dudderidge', '1484794599', 'wdudderidgec@epa.gov', 'Friend', 13);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Serene', 'McCrie', '2588115712', 'sreveleyd@devhub.com', 'Spouse', 14);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Clo', 'Hoggetts', '1709458606', 'choggettse@europa.eu', 'Significant other', 15);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Noemi', 'Woodyer', '9434789205', 'nwoodyerf@skyrock.com', 'Friend', 16);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Ken', 'Strevens', '6966802698', 'kseabrookg@skyrock.com', 'Brother', 17);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Barrie', 'Harg', '4439753859', 'bgalesh@nature.com', 'Brother', 18);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Evan', 'Hammerich', '6016025001', 'ehammerichi@wunderground.com', 'Significant other', 19);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Thorpe', 'Flacke', '8138995083', 'tflackej@creativecommons.org', 'Spouse', 20);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Bale', 'Rustadge', '3696307969', 'brustadgek@networksolutions.com', 'Roommate', 21);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Carlyn', 'Kamien', '4723388259', 'ckamienl@g.co', 'Sister', 22);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Constantine', 'Daykin', '5429949741', 'cdaykinm@wiley.com', 'Brother in law', 23);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Lynn', 'Hek', '6647246631', 'lwalshn@who.int', 'Spouse', 24);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Bliss', 'Cockaday', '5212084949', 'blashleyo@nasa.gov', 'Spouse', 25);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Jerri', 'Frammingham', '8451709715', 'jgelletlyp@apple.com', 'Brother', 26);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Dorey', 'Oldrey', '6507812107', 'doldreyq@privacy.gov.au', 'Friend', 27);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Giacobo', 'Whoolehan', '4277267646', 'gwhoolehanr@facebook.com', 'Friend', 28);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Tyrone', 'Burgise', '5508100380', 'tburgises@goo.gl','Friend', 29);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Mohandas', 'Brydie', '4863441983', 'mbrydiet@homestead.com', 'Roommate', 30);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Gabriell', 'Cleaver', '7498454336', 'glanktreeu@joomla.org', 'Spouse', 31);
INSERT INTO EMERGENCYCONTACT (FirstName, LastName, Phone, Email, Relationship, Employee) VALUES ('Lauritz', 'O'' Finan', '6314413111', 'lofinanv@usda.gov', 'Friend', 32);
